### ISSUE TITLE
Maintaining the repo?

### ISSUE THREAD

**Issue by shmerl** [zfigura/wine#19]
Is this repo maintained? I.e. how can esync be used with current Wine master?

**Comment by zfigura** [comment]
The prescribed approach has always been to cherry-pick the patch set into a Wine tree, but this will clearly cause conflicts against current Wine since the protocol version has been bumped since then. For various reasons I don't intend to rebase the esync branch, so I will have to consider what else I can do to keep cherry-picking possible.

**Comment by zfigura** [comment]
I've created a new branch `esync-rebased` based on master with the patches cherry-picked.

**Comment by shmerl** [comment]
Thanks! Are you going to periodically rebase it on new releases? Also, isn't this something that Proton project should resolve too, or they aren't updating the Wine they are based on?

**Comment by zfigura** [comment]
I'll try to keep it updated, yes. Proton update will be resolved internally.

**Comment by shmerl** [comment]
Are you still maintaining it? The repo looks abandoned. Does anyone keep a rebased branch up to date anywhere?
