### ISSUE TITLE
Error messages spam when running the Epic Game launcher.

### ISSUE THREAD

**Issue by zefkerr** [zfigura/wine#23]
Arch Linux, Wine Staging git (4.0-RC2), using the [wine-tkg-git](https://github.com/Tk-Glitch/PKGBUILDS) with Esync patches.
![screenshot from 2018-12-17 23-35-54](https://user-images.githubusercontent.com/36989404/50107665-12a83500-0255-11e9-9f0a-5146db960d71.png)

**Comment by zfigura** [comment]
Does this cause any noticeable problems? If so, can you please attach a log with +esync,+server?

**Comment by zefkerr** [comment]
[epic_games_launcher-log.zip](https://github.com/zfigura/wine/files/2687675/epic_games_launcher-log.zip)

**Comment by zfigura** [comment]
Could you please describe what symptoms the application displays?

**Comment by zefkerr** [comment]
Using Esync does not change the behavior of the application except for the appearance of these error messages in the terminal, but I assumed that this terminal output could be a bug, so it might be interesting for you.

**Comment by zfigura** [comment]
It's a potential bug, but until it's known to break something, not especially worth fixing. Closing this report until then.

**Comment by zefkerr** [comment]
But what means this terminal output?

**Comment by zfigura** [comment]
The application tried to wait on two handles of different types, one that works with esync and one that doesn't. In this case they were an event and a change notification handle. The fallback is to only wait on the ones that esync can handle, so in this case the change notification handle is never signaled. That this doesn't cause any hangs is not especially surprising, I guess. I think Steam does a similar thing. It can be fixed by adding esync fds to change notification objects, but this is some amount of work and so not something I'm especially concerned about.

**Comment by zefkerr** [comment]
@zfigura  Thank you!
